"""dodanie nazwy ogranoidu

Revision ID: 7bafb05a951c
Revises: 6cb24f42691f
Create Date: 2026-01-24 15:08:44.028668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bafb05a951c'
down_revision = '6cb24f42691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organoids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organoids', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
