"""logi

Revision ID: afd1b09195f2
Revises: d02e5f8f9f82
Create Date: 2026-02-01 19:30:21.777003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd1b09195f2'
down_revision = 'd02e5f8f9f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('organoid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organoid_id'], ['organoids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_logs')
    # ### end Alembic commands ###
