"""dodanie flag stanu zbiorów danych dla organoidów

Revision ID: d02e5f8f9f82
Revises: 7bafb05a951c
Create Date: 2026-01-27 19:29:49.586135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02e5f8f9f82'
down_revision = '7bafb05a951c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organoids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_initialized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_processed_glb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_in_current_rd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organoids', schema=None) as batch_op:
        batch_op.drop_column('is_in_current_rd')
        batch_op.drop_column('is_processed_glb')
        batch_op.drop_column('is_initialized')

    # ### end Alembic commands ###
